test

diff --git a/ci-commit-ios b/ci-commit-ios
--- a/ci-commit-ios
+++ b/ci-commit-ios
@@ -8,18 +8,18 @@ echo "  tested root dir: " ${weexPath}
 echo "************************ build tested app ************************"
 cd ${weexPath}/ios/playground
 
-pod update
+# pod update
 
-xcodebuild -scheme WeexUITestDemo -destination "name=iPhone 6" -workspace WeexDemo.xcworkspace -configuration Debug clean build
-rc=$?
-if [[ $rc != 0 ]] ; then
-    echo "ios run build app: ios run build app failure,break ios running~ " >> ${resultPath}/run-result.log
-    exit $rc
-fi
+# xcodebuild -scheme WeexUITestDemo -destination "name=iPhone 6" -workspace WeexDemo.xcworkspace -configuration Debug clean build
+# rc=$?
+# if [[ $rc != 0 ]] ; then
+#     echo "ios run build app: ios run build app failure,break ios running~ " >> ${resultPath}/run-result.log
+#     exit $rc
+# fi
 
 cd ${toolPath}
 src1=${weexPath}/package.json
-src2=${HOME}/Documents/weex-npm/package.json
+src2=/home/travis/Documents/weex-npm/package.json
 
 echo ${src2}
 
