test

diff --git a/ci-commit-ios b/ci-commit-ios
--- a/ci-commit-ios
+++ b/ci-commit-ios
@@ -2,8 +2,14 @@
 echo "************************ ci-ios start ************************"
 
 weexPath=`pwd`
-toolPath=${weexPath}/tools
+toolPath=${weexPath}/test/tools
+homePath=/home/travis
 echo "  tested root dir: " ${weexPath}
+
+echo "----------------------------start：run env clear----------------------------"
+cd ${weexPath}
+sh ci-daily-envClear
+echo "----------------------------finish：run env clear----------------------------"
 
 echo "************************ build tested app ************************"
 cd ${weexPath}/ios/playground
@@ -19,13 +25,16 @@ fi
 
 cd ${toolPath}
 src1=${weexPath}/package.json
-src2=/home/travis/Documents/weex-npm/package.json
+src2=${homePath}/Documents/weex-npm/package.json
 
 echo ${src2}
 
 isNoChange=True
 if [ ! -f "$src2" ]; then 
-isNoChange=False
+	isNoChange=False
+	mkdir ${homePath}/Documents/weex-npm
+	mkdir ${homePath}/Documents/weex-npm/src
+	mkdir ${homePath}/Documents/weex-npm/bin
 else
 	isNoChange=`python packageJsonCompare.py -src1=${src1} -src2=${src2}`
 	if [[ $isNoChange != False ]] ; then
@@ -57,3 +66,67 @@ if [[ $isNoChange == False ]] ; then
     fi 
 fi 
 echo "isNoChange:"${isNoChange}
+
+cd ${weexPath}
+#TODO 比较package.json
+ln -s $HOME/Documents/weex-npm/node_modules ./node_modules
+ln -s $HOME/Documents/weex-npm/src/js-framework/node_modules/ ./src/js-framework/node_modules
+ln -s $HOME/Documents/weex-npm/src/h5-render/node_modules/ ./src/h5-render/node_modules
+
+npm run build
+rc=$?
+if [[ $rc != 0 ]] ; then
+    echo "npm run build:run build failure,break flow running~ " >> ${resultPath}/run-result.log
+    exit $rc
+fi 
+
+echo "                                Start local server"
+#npm install weex-transformer@0.3.1
+node ./node_modules/weex-transformer/bin/transformer.js test/tc-h5/*.we -o test/build
+rc=$?
+if [[ $rc != 0 ]] ; then
+    echo "transform we to js:transform we to js failure,break flow running~ " >> ${resultPath}/run-result.log
+    exit $rc
+fi 
+
+(npm run serve & echo "start npm run serve")
+
+echo "************************ prepare for uitest ************************"
+appPath=${weexPath}"/ios/playground/DerivedData/WeexDemo/Build/Products/Debug-iphonesimulator/WeexUITestDemo.app"
+instruments -s devices > ./_temp.log
+PREFIX="iPhone 6s"
+cat ./_temp.log | while read line
+do 
+    if [[ $line == $PREFIX* ]]
+    then
+    	echo $line | sed 's/\(.*\)\[\(.*\)\]\(.*\)/\2/g' > ./_temp.log
+        break
+    fi
+done
+deviceName=`cat ./_temp.log`
+rm -rf ./_temp.log
+
+echo "关闭模拟器"
+killall Simulator
+sleep 5
+echo "启动指定模拟器"
+xcrun instruments -w ${deviceName}
+sleep 5
+echo "安装测试包"
+xcrun simctl install booted ${appPath}
+
+echo "************************ Start Sword Server ************************"
+cd ${weexPath}/test/ios/sword.ios.server.start/bin/
+rm -rf instrument*.trace
+(sh start-server &) 
+
+echo "************************ start uitest ************************"
+cd ${weexPath}/test/ios/sword.ios.weex.test/
+mkdir ${weexPath}/test/ios/sword.ios.weex.test/target
+
+picSaveDir=${weexPath}"test/ios/pic-compare/"
+
+mvn test -Dtest=sword.ios.app.test.iOSWXAHrefTest#testScreen_TC_AHref_Event_Test -DpicSaveDir=${picSaveDir} -DdeviceUuid=${deviceName} -DtestAppPath=${appPath}
+
+
+
